### ISSUE TITLE
parcel-plugin-moon on NPM

### ISSUE THREAD

**Issue by shff** [kbrsh/parcel-plugin-moon#1]
Hi @kbrsh , just noticed you started this project!

I recently started a Moon.js plugin for Parcel and published to `parcel-plugin-moon`, but if you want I can transfer the package name to you.

**Comment by kbrsh** [comment]
Hey! @shff 

Thanks for reaching out! I'd love to have the name transferred for official use and appreciate you implementing it. I actually created [an issue](https://github.com/shff/parcel-plugin-moon/issues/2) two days ago on your repo to let you know.

**Comment by shff** [comment]
@kbrsh Oops, this is weird! Somehow I missed the notification for your issue!

Anyways, I just finished transferring the package ownership to you!

Thanks for the great work with Moon.js!

**Comment by kbrsh** [comment]
No problem and thank you!
